version: '3'
services:
  shikshagraha-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '4300:4300'
      - '4301:4301'
      - '4108:4108'
    environment:
      - NODE_ENV=production
